### ISSUE TITLE
Procedure notes need creating 

### ISSUE THREAD

**Issue by JMathiszig-Lee** [somno/somno#18]
We need procedure notes

Design decision
- one master model for procedure
- individual models for each broad type
- hybrid using pathways

**Comment by davidmiller** [comment]
As a part of anaesthetic details

Procedure Note:

Procedure [List with Snomed]
What Needle [Investigate codes?]
Site [Lookup List]
Technique [Lookup list w. FT]
Ultrasound Y/N
Medication [List with coding]
Medication dose [Numeric, mls]

Procedure list: 
* Cannula
* Nerve Block
* Central Line
* Neuraxial Blockade
