### ISSUE TITLE
Should anaesthetic assessment have a frailty score?

### ISSUE THREAD

**Issue by davidmiller** [somno/somno#39]
One for @JMathiszig-Lee - it's in the model and there's a lookuplist, but not in the UI as of #25 - do we want this still or should we kill it?

**Comment by JMathiszig-Lee** [comment]
We should probably kill it for now. I put it in initially as frailty score was very trendy and it worked really nicely with synonyms but a recent study suggested it's not actually that useful. 

Easy to re-implement if needed later
